### ISSUE TITLE
CLOCK IN REMINDER ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSOMENS-TS#12]
TODAY REPORT HAD ABSENT, BUT CLOCK IN REMINDER MAIL CAME.

**Comment by DHANDAPANISATTANATHAN** [comment]
![ts_issue_06022015](https://cloud.githubusercontent.com/assets/9882142/6078861/dddbff52-ae23-11e4-9cd6-95a45031f7ef.png)

**Comment by lalitharajendiran** [comment]
Issue fixed in v3.0
