### ISSUE TITLE
SSO TS ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSOMENS-TS#16]
**DEFECT OWNER : SAFI
TASK OWNER : PUNI**
1. when updating existing login id -if tht login id is in user stamp of user login details table, that showing FOREIGN KEY CONSTRAINTS ERROR-chk n tell is need to change or any thing need to restrict
2.SUPER ADMIN - SHLD EXIST IN LOGIN UPDATION FORM -FOR THAT ONE VIEW NEED
3.Implement upload file in  SSO TS

**Comment by DHANDAPANISATTANATHAN** [comment]
Task owner: PUNI

4.Uploaded file can view in the forms
5.One folder per LOGIN under MAIN folder.

**Comment by punithavimalraj** [comment]
https://github.com/SSOMENSREPO/SSOMENS-TS/releases/tag/V3.5
