### ISSUE TITLE
SSO TS WORK SCHEDULE SS

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSOMENS-TS#17]
PUNI UPDATE UR DELY AND PATCH DETAIL BELOW SS

https://docs.google.com/a/ssomens.com/spreadsheets/d/14zG8HSD0nOeXhzUFofDOuV7mLGIDxnEYf2UaldWVcLA/edit#gid=0

**Comment by punithavimalraj** [comment]
UPDATED PATCH DETAILS IN SS
