### ISSUE TITLE
ISSUE IN PATCH SP

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSOMENS-TS#18]
DEFECT OWNER: PUNI

IP ADDRESS PATCH SP GOT SYNTAX ERROR ISSUE.
SP_CONFIGURATION_TS_INSERT_IPADDRESS_VER0.1_17042015
CORRECT AND RE DELIVER

**Comment by punithavimalraj** [comment]
corrected n updated in drive
