### ISSUE TITLE
SSO TS DEFECT

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSOMENS-TS#19]
DEFECT OWENR: RD,AI & SA

CLEAR THE BELOW ISSUE ASAP

![issue_13052015](https://cloud.githubusercontent.com/assets/9882142/7607831/d8c2cc6c-f964-11e4-8ad0-b2a39ff8d128.png)

**Comment by lalitharajendiran** [comment]
CLEARED ISSUE IN VER 3.6
