### ISSUE TITLE
SSO TS ISSUES

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSOMENS-TS#20]
**PHASE 1 TESTING:**

**DEFECT OWNER: RD & AI**

**Fix the below SSO TS defect.**
![issue](https://cloud.githubusercontent.com/assets/9882142/7814147/ce23d426-03dd-11e5-83fd-9f391c46f88e.png)

![issue_26052015](https://cloud.githubusercontent.com/assets/9882142/7814153/e242fa68-03dd-11e5-8641-f66d29cc01a7.png)

![ts revenu dt hdrs issue](https://cloud.githubusercontent.com/assets/9882142/7814173/fe4eb59e-03dd-11e5-90a8-1b60332cba0f.png)

**Comment by lalitharajendiran** [comment]
CLEARED ISSUE IN VER 3.8
