### ISSUE TITLE
SSO TS LOGIN CREATION ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSOMENS-TS#21]
<h3>LOGIN NOT CREATE IN SSO TS PROD

DEFECT OWNER:PUNI,

PRIORITY TASK:

![issue_prod_27052015](https://cloud.githubusercontent.com/assets/9882142/7830729/904c8608-046d-11e5-99fa-727a97437865.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
Puni,

Target to close: 03/06/2015

This one need to close,

logiin id Folder  available but it point out some io issue, wrong folder id.

**Comment by punithavimalraj** [comment]
fixed version link

https://github.com/SSOMENSREPO/SSOMENS-TS/releases/tag/v5.3
