### ISSUE TITLE
SSO TS ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSOMENS-TS#22]
DEFECT OWNER: RD & AI

Fix the below defect and dely 28/05/2015

![issue_27052015](https://cloud.githubusercontent.com/assets/9882142/7838516/e8a9896c-04aa-11e5-8f49-fe5c2b7cf222.png)

**Comment by lalitharajendiran** [comment]
CLEARED ISSUE IN VER 3.9,4.0,4.1
