### ISSUE TITLE
ISSUE TS PDF

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSOMENS-TS#6]
![issue_ts_09012015_1](https://cloud.githubusercontent.com/assets/9882142/5676879/8b041b10-9803-11e4-95fc-3cd395260c54.png)

**Comment by lalitharajendiran** [comment]
Issue Fixed in ver 2.7

**Comment by lalitharajendiran** [comment]
Issue fixed in ver 2.7

**Comment by lalitharajendiran** [comment]
Issue fixed in ver 2.7
