### ISSUE TITLE
TS ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSOMENS-TS#8]
1970 ISSUE, PAGINATION, EMAIL TEMPLATE 
![ts_issue_23012015](https://cloud.githubusercontent.com/assets/9882142/5886684/617b9c6e-a3ac-11e4-93fc-b0cef1c99b51.png)
ISSUES

**Comment by lalitharajendiran** [comment]
Issue fixed in v2.9
